# Generated by Django 5.1.1 on 2024-09-13 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.PositiveIntegerField()),
                ('pass_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('car', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('car_number', models.CharField(max_length=255)),
                ('epc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parking_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.pass')),
            ],
        ),
    ]
