# Generated by Django 4.2.16 on 2024-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуска'},
        ),
        migrations.AlterField(
            model_name='pass',
            name='car',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='car_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер автомобиля'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='epc',
            field=models.CharField(max_length=255, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pass_number',
            field=models.PositiveIntegerField(verbose_name='Номер пропуска'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pass_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип пропуска'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Служба'),
        ),
    ]
