# Generated by Django 4.2.16 on 2024-09-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_pass_options_alter_pass_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='pass_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер пропуска'),
        ),
    ]
