# Generated by Django 4.2.16 on 2024-11-17 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_pass_pass_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отмечено'),
        ),
        migrations.AlterField(
            model_name='history',
            name='parking_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.pass', verbose_name='Номер пропуска'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='epc',
            field=models.CharField(max_length=255, unique=True, verbose_name='Метка'),
        ),
    ]
